# Generated by Django 5.2.17 on 2026-09-11 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='RESERVED', max_length=20)),
                ('reservation_code', models.CharField(editable=False, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('food_listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='food.foodlisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='reservation_custome_e440be_idx'), models.Index(fields=['food_listing', 'status'], name='reservation_food_li_78350c_idx')],
            },
        ),
    ]
