# Generated by Django 5.2.17 on 2026-09-11 05:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('RICE', 'Rice'), ('NOODLES', 'Noodles'), ('CHICKEN', 'Chicken'), ('FAST_FOOD', 'Fast Food'), ('BAKERY', 'Bakery'), ('DESSERT', 'Dessert'), ('DRINKS', 'Drinks'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food/')),
                ('image_url', models.URLField(blank=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_percentage', models.PositiveSmallIntegerField(default=50)),
                ('discounted_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('pickup_date', models.DateField(default=django.utils.timezone.localdate)),
                ('pickup_start', models.TimeField()),
                ('pickup_end', models.TimeField()),
                ('pickup_location', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD_OUT', 'Sold Out'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_listings', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['pickup_date', 'pickup_end', '-created_at'],
                'indexes': [models.Index(fields=['status', 'pickup_date'], name='food_foodli_status_edeac0_idx'), models.Index(fields=['category', 'status'], name='food_foodli_categor_a8d6fa_idx'), models.Index(fields=['restaurant', 'status'], name='food_foodli_restaur_14e4a1_idx')],
            },
        ),
    ]
